# Generated by Django 3.2.6 on 2021-12-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
