# Generated by Django 3.2.6 on 2021-12-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_fooditem_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='qty',
        ),
    ]
