# Generated by Django 3.2.6 on 2022-01-15 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatit', '0002_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userNumber', to=settings.AUTH_USER_MODEL),
        ),
    ]
