# Generated by Django 3.2.6 on 2022-01-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatit', '0003_alter_mobilenumber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
