# Generated by Django 3.2.6 on 2022-01-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatit', '0004_rename_orderdetails_activeorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorders',
            name='cart',
        ),
        migrations.AddField(
            model_name='activeorders',
            name='cart',
            field=models.ManyToManyField(to='eatit.Cart'),
        ),
    ]
