# Generated by Django 3.2.6 on 2022-01-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatit', '0008_alter_activeorders_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorders',
            name='cart',
            field=models.ManyToManyField(default=None, null=True, to='eatit.Cart'),
        ),
    ]
