# Generated by Django 3.2.6 on 2022-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatit', '0009_alter_activeorders_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorders',
            name='cart',
        ),
        migrations.AddField(
            model_name='activeorders',
            name='userCart',
            field=models.ManyToManyField(to='eatit.Cart'),
        ),
    ]
