# Generated by Django 3.2.6 on 2022-01-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatit', '0010_auto_20220104_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeorders',
            old_name='userCart',
            new_name='cart',
        ),
    ]
